<template>
    <div>
        <!-- Draft for your perusal -->
        <p class='mb-0 font-weight-light lh-28'>Zebu Share and Wealth Managements Private Limited is a trading member of NSE, BSE and MCX and with SEBI Registration No: INZ000174634. Further, Zebu Share and Wealth Managements Private Limited (hereinafter referred as 'Zebu') is also a Research Analyst bearing SEBI Registration No. INH200006044. Zebu is not an Investment Adviser. Information herein should be regarded as a resource only and should be used at one's own risk. This information/report is prepared for the purpose of private circulation among the clients of Zebu free of cost for their sole use and not for circulation. No part of the report/information shall be reproduced in any format without prior written permission from the author/Zebu. This report is not available separately for sale/subscription. This is not an offer to sell or solicitation to buy any securities and Zebu will not be liable for any losses incurred or investment(s) made or decisions taken/or not taken based on the information provided herein. Information contained herein does not constitute investment advice or a personal recommendation or take into account the particular investment objectives, financial situations, or needs of individual subscribers. Before acting on any recommendation, recipients of this information should consider whether it is suitable for their particular circumstances and, if necessary, seek an independent professional advice from a SEBI registered Investment Adviser. This is not directed for access or use by anyone in a country, especially, USA, Canada or the European Union countries, where such use or access is unlawful or which may subject Zebu or its affiliates to any registration or licensing requirement. All content and information are provided on an 'as is' basis by Zebu. Information herein is believed to be reliable but Zebu does not warrant its completeness or accuracy and expressly disclaims all warranties and conditions of any kind, whether express or implied. Zebu may hold shares in the company/ies discussed herein. As a condition to accessing Zebu content and website, you agree to our Terms and Conditions of Use, available and updated from time to time in its website.</p>
        <p class='font-weight-bold title'>DISCLOSURE WITH REGARDS TO OWNERSHIP AND MATERIAL CONFLICTS OF INTEREST:</p>
        <p class='mb-0 font-weight-light lh-28'>
            <ul>
                <li>'Subject Company' is a company/index on which a buy/sell/hold view or target price is given/changed in this Research Report.</li>
                 <li> Research Analyst or his/her relative or Zebu does not have any financial interest in the subject company.</li>
                  <li>Zebu and its affiliated company(ies), their directors and employees may; (a) from time to time, have a long or short position in, and buy or sell the securities (Subject Company) of the company(ies) mentioned herein or (b) be engaged in any other transaction involving such securities and earn brokerage or other compensation of the company(ies) discussed or may have any other potential conflict of interests with respect to any recommendation and other related information and opinions given.</li>
                   <li>Zebu and other group companies, its directors, associates, employees may have various positions in any of the stocks, securities and financial instruments dealt in the report, or may make sell or purchase or other deals in these securities from time to time or may deal in other securities of the companies / organizations described in this report.</li>
                    <li>Research Analyst or his relative or Zebu or its Associate may have beneficial ownership of 1% or more in the subject company at the end of the month immediately preceding the date of publication of the Research Report/information.</li>
                </ul></p>
                <p class="font-weight-bold title">DISCLOSURE WITH REGARDS TO OWNERSHIP AND MATERIAL CONFLICTS OF INTEREST:</p>
                <p class='mb-0 font-weight-light lh-28'><ul>
                    <li>Neither Zebu nor its Associates have received any compensation from the subject company in the past twelve months.</li>
                    <li>Neither Zebu nor its Associates have managed or co-managed public offering of securities for the subject company in the past twelve months.</li>
                    <li> Neither Zebu nor its Associates have received any compensation for investment banking or merchant banking or brokerage services from the subject company in the past twelve months.</li>
                    <li>Neither Zebu nor its Associates have received any compensation for products or services other than investment banking or merchant banking or brokerage services from the subject company in the past twelve months.</li>
                    <li>Neither Zebu nor its Associates have received any compensation or other benefits from the subject company or third party in connection with the research report.</li>
                </ul></p>
                <p class='font-weight-bold title'>General Disclosure/Disclaimer:</p>
                <p class='mb-0 font-weight-light lh-28'>I, V Vijayakumar, author and the name subscribed to this report, hereby certify that all of the views expressed in this research report accurately reflect our views about the subject issuer(s) or securities. Zebu has no material adverse disciplinary history as on the date of publication of this report. We also certify that no part of our compensation was, is, or will be directly or indirectly related to the specific recommendation(s) or view(s) in this report.<br><br>Zebu, its directors, analysts or employees do not take any responsibility, financial or otherwise, of the losses or the damages sustained due to the investments made or any action taken on basis of this report, including but not restricted to, fluctuation in the prices of shares and bonds, changes in the currency rates, diminution in the NAVs, reduction in the dividend or income, etc.</p> -->


            



    </div>
</template>

<script>
export default {
  data() {
    return {
       Holdings:[
        {
            title:"Draft For Your Perusal",
            content:"<p class='mb-0 font-weight-light lh-28'>Zebu Share and Wealth Managements Private Limited is a trading member of NSE, BSE and MCX and with SEBI Registration No: INZ000174634. Further, Zebu Share and Wealth Managements Private Limited (hereinafter referred as 'Zebu') is also a Research Analyst bearing SEBI Registration No. INH200006044. Zebu is not an Investment Adviser. Information herein should be regarded as a resource only and should be used at one's own risk. This information/report is prepared for the purpose of private circulation among the clients of Zebu free of cost for their sole use and not for circulation. No part of the report/information shall be reproduced in any format without prior written permission from the author/Zebu. This report is not available separately for sale/subscription. This is not an offer to sell or solicitation to buy any securities and Zebu will not be liable for any losses incurred or investment(s) made or decisions taken/or not taken based on the information provided herein. Information contained herein does not constitute investment advice or a personal recommendation or take into account the particular investment objectives, financial situations, or needs of individual subscribers. Before acting on any recommendation, recipients of this information should consider whether it is suitable for their particular circumstances and, if necessary, seek an independent professional advice from a SEBI registered Investment Adviser. This is not directed for access or use by anyone in a country, especially, USA, Canada or the European Union countries, where such use or access is unlawful or which may subject Zebu or its affiliates to any registration or licensing requirement. All content and information are provided on an 'as is' basis by Zebu. Information herein is believed to be reliable but Zebu does not warrant its completeness or accuracy and expressly disclaims all warranties and conditions of any kind, whether express or implied. Zebu may hold shares in the company/ies discussed herein. As a condition to accessing Zebu content and website, you agree to our Terms and Conditions of Use, available and updated from time to time in its website.</p>",
        },
        {
            title:"Ownership And Material",
            content:"<p class='font-weight-bold title'>DISCLOSURE WITH REGARDS TO OWNERSHIP AND MATERIAL CONFLICTS OF INTEREST:</p><p class='mb-0 font-weight-light lh-28'><ul><li>'Subject Company' is a company/index on which a buy/sell/hold view or target price is given/changed in this Research Report.</li><li> Research Analyst or his/her relative or Zebu does not have any financial interest in the subject company.</li><li>Zebu and its affiliated company(ies), their directors and employees may; (a) from time to time, have a long or short position in, and buy or sell the securities (Subject Company) of the company(ies) mentioned herein or (b) be engaged in any other transaction involving such securities and earn brokerage or other compensation of the company(ies) discussed or may have any other potential conflict of interests with respect to any recommendation and other related information and opinions given.</li><li>Zebu and other group companies, its directors, associates, employees may have various positions in any of the stocks, securities and financial instruments dealt in the report, or may make sell or purchase or other deals in these securities from time to time or may deal in other securities of the companies / organizations described in this report.</li><li>Research Analyst or his relative or Zebu or its Associate may have beneficial ownership of 1% or more in the subject company at the end of the month immediately preceding the date of publication of the Research Report/information.</li></ul></p>"
        },
        {
            title:"Receipt Of Compensation",
            content:"<p class='font-weight-bold title'>DISCLOSURE WITH REGARDS TO OWNERSHIP AND MATERIAL CONFLICTS OF INTEREST:</p><p class='mb-0 font-weight-light lh-28'><ul><li>Neither Zebu nor its Associates have received any compensation from the subject company in the past twelve months.</li><br><li>Neither Zebu nor its Associates have managed or co-managed public offering of securities for the subject company in the past twelve months.</li><br><li> Neither Zebu nor its Associates have received any compensation for investment banking or merchant banking or brokerage services from the subject company in the past twelve months.</li><br><li>Neither Zebu nor its Associates have received any compensation for products or services other than investment banking or merchant banking or brokerage services from the subject company in the past twelve months.</li><br><li>Neither Zebu nor its Associates have received any compensation or other benefits from the subject company or third party in connection with the research report.</li></ul></p>",
        },

        {
            title:"General Disclosure/Disclaimer:",
            content:"<p class='font-weight-bold title'>General Disclosure/Disclaimer:</p><p class='mb-0 font-weight-light lh-28'>I, V Vijayakumar, author and the name subscribed to this report, hereby certify that all of the views expressed in this research report accurately reflect our views about the subject issuer(s) or securities. Zebu has no material adverse disciplinary history as on the date of publication of this report. We also certify that no part of our compensation was, is, or will be directly or indirectly related to the specific recommendation(s) or view(s) in this report.<br><br>Zebu, its directors, analysts or employees do not take any responsibility, financial or otherwise, of the losses or the damages sustained due to the investments made or any action taken on basis of this report, including but not restricted to, fluctuation in the prices of shares and bonds, changes in the currency rates, diminution in the NAVs, reduction in the dividend or income, etc.</p>"
          }
       
       ]
    };
  },

}
</script>